### ISSUE TITLE
Add cli commands

### ISSUE THREAD

**Issue by skudlur** [acmpesuecc/riscv-instr-gen#2]
# Description
cli commands like `--generate`, `--isa` and so on can be added to create a basic CLI tool. Please refer to `utils.py` for context on what these commands will do.

# Note
* Bounty points are allotted based the number of commands you add. Base points are tagged, the brownie points will be allotted by the maintainer.

**Comment by KunalMaverick** [comment]
can i get assigned to this

**Comment by skudlur** [comment]
@KunalMaverick assigned

**Comment by sid-nc** [comment]
can i get assigned

**Comment by rahuljjacob** [comment]
can i get assigned this issue next ?

**Comment by skudlur** [comment]
@sid-nc assigned

**Comment by sid-nc** [comment]
working on it

**Comment by sid-nc** [comment]
have you received the pr

**Comment by skudlur** [comment]
@sid-nc no

**Comment by sid-nc** [comment]
but i did it.
can u tell me how to do it so that i can cross check

**Comment by skudlur** [comment]
@sid-nc I don't see the pr, please refer to github guide and open a pr

**Comment by sid-nc** [comment]
#======================================================
#	RISC-V Instruction Generator
#	Testing your cores, sims and ems made simpler!
#======================================================

# Imports
`import os
import click
import sys

import argparse

# Function to generate instructions based on the 
def generate_instructions(isa):
    r1 = RV_instruction_generator(isa)
    r1.isa_format_check()
    r1.instr_gen()

# To create a CLI parser
def create_parser():
    parser = argparse.ArgumentParser(description="RISC-V Instruction Generator")
    parser.add_argument(
        "--generate",
        type=str,
        choices=i_list,  # Limit choices to valid instruction types
        help="Specify the instruction type to generate",
    )
    parser.add_argument(
        "--isa",
        type=str,
        required=True,
        help="Specify the RISC-V Instruction Set Architecture (e.g., RV32I, RV64I)",
    )
    return parser

# Main function
def main():
    # Create the CLI parser
    parser = create_parser()

    # Parse command-line arguments
    args = parser.parse_args()

    # If --generate is specified, generate the instructions
    if args.generate:
        print(f"Generating {args.generate} instructions for ISA {args.isa}...")
        generate_instructions(args.isa)
    else:
        print("No instruction type specified. Use --generate to specify an instruction type.")

if __name__ == "__main__":
    main()



# CLI`

**Comment by sid-nc** [comment]
can u check for the pr now

**Comment by RitwikAg120** [comment]
I WANT TO GET ASSIGNED ON THIS!!

**Comment by skudlur** [comment]
Closing this issue because #4 fixed this first. Please await for the next issue
